//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.1
=======
//     Runtime Version:4.0.30319.17929
>>>>>>> b91248b245becf9c7a2599c068cb746da03d430a
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMSDataLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHAWAJA\\KHAWAJA;Initial Catalog=SCMS;Persist Security Info=True;User " +
            "ID=sa;Password=1234")]
        public string SCMSConnectionString {
            get {
                return ((string)(this["SCMSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AWAIS-PC\\SQLEXPRESS;Initial Catalog=SCMS;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string SCMSConnectionString1 {
            get {
                return ((string)(this["SCMSConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WAQAS\\KHAWAJAWAQAS;Initial Catalog=SCMS;Persist Security Info=True;Us" +
            "er ID=sa;Password=1234")]
        public string SCMSConnectionString2 {
            get {
                return ((string)(this["SCMSConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WAQAS\\KHAWAJAWAQAS;Initial Catalog=SCMS;Persist Security Info=True;Us" +
            "er ID=sa")]
        public string SCMSConnectionString3 {
            get {
                return ((string)(this["SCMSConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AWAIS-PC\\SQLEXPRESS;Initial Catalog=SCMS;Persist Security Info=True;U" +
            "ser ID=sa;Password=Door123")]
        public string SCMSConnectionString4 {
            get {
                return ((string)(this["SCMSConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JAWAD\\JAWAD;Initial Catalog=SCMS;Persist Security Info=True;User ID=s" +
            "a;Password=admin123")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Home_PC_2;Initial Catalog=SCMS;Persist Security Info=True;User ID=sa;" +
            "Password=Boingo36!")]
>>>>>>> b91248b245becf9c7a2599c068cb746da03d430a
        public string SCMSConnectionString5 {
            get {
                return ((string)(this["SCMSConnectionString5"]));
            }
        }
    }
}
