<?xml version="1.0" encoding="utf-8"?><Database Name="SCMS" Class="SCMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JAWAD\JAWAD;Initial Catalog=SCMS;Persist Security Info=True;User ID=sa" SettingsObjectName="SCMSDataLayer.Properties.Settings" SettingsPropertyName="SCMSConnectionString5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GL_VchrDetail" Member="GL_VchrDetails">
    <Type Name="GL_VchrDetail">
      <Column Name="VchDet_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VchMas_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChrtAcc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchMas_DrAmount" Type="System.Decimal" DbType="Decimal(20,6)" CanBeNull="true" />
      <Column Name="VchMas_CrAmount" Type="System.Decimal" DbType="Decimal(20,6)" CanBeNull="true" />
      <Column Name="VchDet_Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="GL_VchrMaster_GL_VchrDetail" Member="GL_VchrMaster" ThisKey="VchMas_Id" OtherKey="VchMas_Id" Type="GL_VchrMaster" IsForeignKey="true" />
      <Association Name="SETUP_ChartOfAccount_GL_VchrDetail" Member="SETUP_ChartOfAccount" ThisKey="ChrtAcc_Id" OtherKey="ChrtAcc_Id" Type="SETUP_ChartOfAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYSTEM_Nature" Member="SYSTEM_Natures">
    <Type Name="SYSTEM_Nature">
      <Column Name="Natr_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Natr_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Natr_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Natr_Default" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Natr_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SYSTEM_Nature_SETUP_ChartOfAccount" Member="SETUP_ChartOfAccounts" ThisKey="Natr_Id" OtherKey="Natr_Id" Type="SETUP_ChartOfAccount" />
    </Type>
  </Table>
  <Table Name="dbo.GL_VchrMaster" Member="GL_VchrMasters">
    <Type Name="GL_VchrMaster">
      <Column Name="VchMas_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VchMas_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchMas_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchMas_Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VchMas_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchMas_EnteredBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchMas_EnteredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VchMas_ApprovedBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchMas_ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="GL_VchrMaster_GL_VchrDetail" Member="GL_VchrDetails" ThisKey="VchMas_Id" OtherKey="VchMas_Id" Type="GL_VchrDetail" />
      <Association Name="SETUP_Company_GL_VchrMaster" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_GL_VchrMaster" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
      <Association Name="SETUP_VoucherType_GL_VchrMaster" Member="SETUP_VoucherType" ThisKey="VchrType_Id" OtherKey="VchrType_Id" Type="SETUP_VoucherType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pbcatcol" Member="pbcatcols">
    <Type Name="pbcatcol">
      <Column Name="pbc_tnam" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="pbc_tid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pbc_ownr" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="pbc_cnam" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="pbc_cid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbc_labl" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="pbc_lpos" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbc_hdr" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="pbc_hpos" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbc_jtfy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbc_mask" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="pbc_case" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbc_hght" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbc_wdth" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbc_ptrn" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="pbc_bmap" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pbc_init" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="pbc_cmnt" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="pbc_edit" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="pbc_tag" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pbcatedt" Member="pbcatedts">
    <Type Name="pbcatedt">
      <Column Name="pbe_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="pbe_edit" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="pbe_type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="pbe_cntr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pbe_seqn" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="pbe_flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pbe_work" Type="System.String" DbType="Char(32)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pbcatfmt" Member="pbcatfmts">
    <Type Name="pbcatfmt">
      <Column Name="pbf_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="pbf_frmt" Type="System.String" DbType="VarChar(254) NOT NULL" CanBeNull="false" />
      <Column Name="pbf_type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="pbf_cntr" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pbcattbl" Member="pbcattbls">
    <Type Name="pbcattbl">
      <Column Name="pbt_tnam" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="pbt_tid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pbt_ownr" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="pbd_fhgt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbd_fwgt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbd_fitl" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pbd_funl" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pbd_fchr" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbd_fptc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbd_ffce" Type="System.String" DbType="Char(32)" CanBeNull="true" />
      <Column Name="pbh_fhgt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbh_fwgt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbh_fitl" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pbh_funl" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pbh_fchr" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbh_fptc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbh_ffce" Type="System.String" DbType="Char(32)" CanBeNull="true" />
      <Column Name="pbl_fhgt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbl_fwgt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbl_fitl" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pbl_funl" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pbl_fchr" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbl_fptc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pbl_ffce" Type="System.String" DbType="Char(32)" CanBeNull="true" />
      <Column Name="pbt_cmnt" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pbcatvld" Member="pbcatvlds">
    <Type Name="pbcatvld">
      <Column Name="pbv_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="pbv_vald" Type="System.String" DbType="VarChar(254) NOT NULL" CanBeNull="false" />
      <Column Name="pbv_type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="pbv_cntr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pbv_msg" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Security_MenuOptions" Member="Security_MenuOptions">
    <Type Name="Security_MenuOption">
      <Column Name="Mnu_Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Mnu_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mnu_Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Mnu_Level" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mnu_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mnu_TargetUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Mnu_IsLineBreak" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Mnu_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Security_MenuOption_Security_UserRight" Member="Security_UserRights" ThisKey="Mnu_Id" OtherKey="Mnu_Id" Type="Security_UserRight" />
    </Type>
  </Table>
  <Table Name="dbo.SECURITY_User" Member="SECURITY_Users">
    <Type Name="SECURITY_User">
      <Column Name="User_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="User_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsrGrp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="User_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="User_Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="User_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SECURITY_UserGroup_SECURITY_User" Member="SECURITY_UserGroup" ThisKey="UsrGrp_Id" OtherKey="UsrGrp_Id" Type="SECURITY_UserGroup" IsForeignKey="true" />
      <Association Name="SETUP_Company_SECURITY_User" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SECURITY_User" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SECURITY_UserGroup" Member="SECURITY_UserGroups">
    <Type Name="SECURITY_UserGroup">
      <Column Name="UsrGrp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UsrGrp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsrGrp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UsrGrp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsrGrp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SECURITY_UserGroup_SECURITY_User" Member="SECURITY_Users" ThisKey="UsrGrp_Id" OtherKey="UsrGrp_Id" Type="SECURITY_User" />
      <Association Name="SETUP_Company_SECURITY_UserGroup" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SECURITY_UserGroup" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Security_UserRights" Member="Security_UserRights">
    <Type Name="Security_UserRight">
      <Column Name="UsrSec_Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UsrSec_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Grp_Id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mnu_Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UsrSec_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Security_MenuOption_Security_UserRight" Member="Security_MenuOption" ThisKey="Mnu_Id" OtherKey="Mnu_Id" Type="Security_MenuOption" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_Bank" Member="SETUP_Banks">
    <Type Name="SETUP_Bank">
      <Column Name="Bank_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Bank_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Bank_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Bank_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bank_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_Bank_SETUP_BankAccount" Member="SETUP_BankAccounts" ThisKey="Bank_Id" OtherKey="Bank_Id" Type="SETUP_BankAccount" />
      <Association Name="SETUP_Company_SETUP_Bank" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_Bank" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_BankAccount" Member="SETUP_BankAccounts">
    <Type Name="SETUP_BankAccount">
      <Column Name="BankAcc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BankAcc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Bank_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankAcc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BankAcc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankAcc_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_Bank_SETUP_BankAccount" Member="SETUP_Bank" ThisKey="Bank_Id" OtherKey="Bank_Id" Type="SETUP_Bank" IsForeignKey="true" />
      <Association Name="SETUP_Company_SETUP_BankAccount" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_BankAccount" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_Calendar" Member="SETUP_Calendars">
    <Type Name="SETUP_Calendar">
      <Column Name="Cldr_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cldr_ParentRefId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cldr_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CldrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cldr_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cldr_DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cldr_DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cldr_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cldr_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CldrType_Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_CalendarType_SETUP_Calendar" Member="SETUP_CalendarType" ThisKey="CldrType_Id" OtherKey="CldrType_Id" Type="SETUP_CalendarType" IsForeignKey="true" />
      <Association Name="SETUP_Company_SETUP_Calendar" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_Calendar" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_CalendarType" Member="SETUP_CalendarTypes">
    <Type Name="SETUP_CalendarType">
      <Column Name="CldrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CldrType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CldrType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CldrType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CldrType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CldrType_Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_CalendarType_SETUP_Calendar" Member="SETUP_Calendars" ThisKey="CldrType_Id" OtherKey="CldrType_Id" Type="SETUP_Calendar" />
      <Association Name="SETUP_Company_SETUP_CalendarType" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_CalendarType" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_ChartOfAccount" Member="SETUP_ChartOfAccounts">
    <Type Name="SETUP_ChartOfAccount">
      <Column Name="ChrtAcc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChrtAcc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Natr_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccNatr_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChrtAcc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ChrtAcc_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_BudgetLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_ChartOfAccount_GL_VchrDetail" Member="GL_VchrDetails" ThisKey="ChrtAcc_Id" OtherKey="ChrtAcc_Id" Type="GL_VchrDetail" />
      <Association Name="SYSTEM_Nature_SETUP_ChartOfAccount" Member="SYSTEM_Nature" ThisKey="Natr_Id" OtherKey="Natr_Id" Type="SYSTEM_Nature" IsForeignKey="true" />
      <Association Name="SETUP_Company_SETUP_ChartOfAccount" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_ChartOfAccount" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
      <Association Name="SYSTEM_AccountNature_SETUP_ChartOfAccount" Member="SYSTEM_AccountNature" ThisKey="AccNatr_Id" OtherKey="AccNatr_Id" Type="SYSTEM_AccountNature" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_City" Member="SETUP_Cities">
    <Type Name="SETUP_City">
      <Column Name="City_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="City_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cnty_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_City_SETUP_Customer" Member="SETUP_Customers" ThisKey="City_Id" OtherKey="City_Id" Type="SETUP_Customer" />
      <Association Name="SETUP_City_SETUP_Supplier" Member="SETUP_Suppliers" ThisKey="City_Id" OtherKey="City_Id" Type="SETUP_Supplier" />
      <Association Name="SETUP_Country_SETUP_City" Member="SETUP_Country" ThisKey="Cnty_Id" OtherKey="Cnty_Id" Type="SETUP_Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_Company" Member="SETUP_Companies">
    <Type Name="SETUP_Company">
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cmp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Phone" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Fax" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cmp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_Company_GL_VchrMaster" Member="GL_VchrMasters" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="GL_VchrMaster" />
      <Association Name="SETUP_Company_SECURITY_User" Member="SECURITY_Users" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SECURITY_User" />
      <Association Name="SETUP_Company_SECURITY_UserGroup" Member="SECURITY_UserGroups" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SECURITY_UserGroup" />
      <Association Name="SETUP_Company_SETUP_Bank" Member="SETUP_Banks" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Bank" />
      <Association Name="SETUP_Company_SETUP_BankAccount" Member="SETUP_BankAccounts" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_BankAccount" />
      <Association Name="SETUP_Company_SETUP_Calendar" Member="SETUP_Calendars" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Calendar" />
      <Association Name="SETUP_Company_SETUP_CalendarType" Member="SETUP_CalendarTypes" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_CalendarType" />
      <Association Name="SETUP_Company_SETUP_ChartOfAccount" Member="SETUP_ChartOfAccounts" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_ChartOfAccount" />
      <Association Name="SETUP_Company_SETUP_Customer" Member="SETUP_Customers" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Customer" />
      <Association Name="SETUP_Company_SETUP_CustomerType" Member="SETUP_CustomerTypes" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_CustomerType" />
      <Association Name="SETUP_Company_SETUP_Location" Member="SETUP_Locations" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Location" />
      <Association Name="SETUP_Company_SETUP_Supplier" Member="SETUP_Suppliers" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Supplier" />
      <Association Name="SETUP_Company_SETUP_SupplierType" Member="SETUP_SupplierTypes" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_SupplierType" />
      <Association Name="SETUP_Company_SETUP_VoucherType" Member="SETUP_VoucherTypes" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_VoucherType" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_Country" Member="SETUP_Countries">
    <Type Name="SETUP_Country">
      <Column Name="Cnty_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cnty_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cnty_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cnty_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cnty_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_Country_SETUP_City" Member="SETUP_Cities" ThisKey="Cnty_Id" OtherKey="Cnty_Id" Type="SETUP_City" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_Customer" Member="SETUP_Customers">
    <Type Name="SETUP_Customer">
      <Column Name="Cust_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cust_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cust_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cust_Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cust_Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cust_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cust_Phone" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cust_Fax" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cust_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cust_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_City_SETUP_Customer" Member="SETUP_City" ThisKey="City_Id" OtherKey="City_Id" Type="SETUP_City" IsForeignKey="true" />
      <Association Name="SETUP_Company_SETUP_Customer" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_CustomerType_SETUP_Customer" Member="SETUP_CustomerType" ThisKey="CustType_Id" OtherKey="CustType_Id" Type="SETUP_CustomerType" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_Customer" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_CustomerType" Member="SETUP_CustomerTypes">
    <Type Name="SETUP_CustomerType">
      <Column Name="CustType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CustType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_CustomerType_SETUP_Customer" Member="SETUP_Customers" ThisKey="CustType_Id" OtherKey="CustType_Id" Type="SETUP_Customer" />
      <Association Name="SETUP_Company_SETUP_CustomerType" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_CustomerType" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_Location" Member="SETUP_Locations">
    <Type Name="SETUP_Location">
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Loc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Loc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loc_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_Location_GL_VchrMaster" Member="GL_VchrMasters" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="GL_VchrMaster" />
      <Association Name="SETUP_Location_SECURITY_User" Member="SECURITY_Users" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SECURITY_User" />
      <Association Name="SETUP_Location_SECURITY_UserGroup" Member="SECURITY_UserGroups" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SECURITY_UserGroup" />
      <Association Name="SETUP_Location_SETUP_Bank" Member="SETUP_Banks" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Bank" />
      <Association Name="SETUP_Location_SETUP_BankAccount" Member="SETUP_BankAccounts" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_BankAccount" />
      <Association Name="SETUP_Location_SETUP_Calendar" Member="SETUP_Calendars" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Calendar" />
      <Association Name="SETUP_Location_SETUP_CalendarType" Member="SETUP_CalendarTypes" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_CalendarType" />
      <Association Name="SETUP_Location_SETUP_ChartOfAccount" Member="SETUP_ChartOfAccounts" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_ChartOfAccount" />
      <Association Name="SETUP_Location_SETUP_Customer" Member="SETUP_Customers" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Customer" />
      <Association Name="SETUP_Location_SETUP_CustomerType" Member="SETUP_CustomerTypes" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_CustomerType" />
      <Association Name="SETUP_Location_SETUP_Supplier" Member="SETUP_Suppliers" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Supplier" />
      <Association Name="SETUP_Location_SETUP_SupplierType" Member="SETUP_SupplierTypes" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_SupplierType" />
      <Association Name="SETUP_Location_SETUP_VoucherType" Member="SETUP_VoucherTypes" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_VoucherType" />
      <Association Name="SETUP_Company_SETUP_Location" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_Supplier" Member="SETUP_Suppliers">
    <Type Name="SETUP_Supplier">
      <Column Name="Supp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Supp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuppType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Supp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supp_Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supp_Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supp_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supp_Phone" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supp_Fax" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Supp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_Company_SETUP_Supplier" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_Supplier" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
      <Association Name="SETUP_City_SETUP_Supplier" Member="SETUP_City" ThisKey="City_Id" OtherKey="City_Id" Type="SETUP_City" IsForeignKey="true" />
      <Association Name="SETUP_SupplierType_SETUP_Supplier" Member="SETUP_SupplierType" ThisKey="SuppType_Id" OtherKey="SuppType_Id" Type="SETUP_SupplierType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_SupplierType" Member="SETUP_SupplierTypes">
    <Type Name="SETUP_SupplierType">
      <Column Name="SuppType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SuppType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuppType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SuppType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SuppType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_SupplierType_SETUP_Supplier" Member="SETUP_Suppliers" ThisKey="SuppType_Id" OtherKey="SuppType_Id" Type="SETUP_Supplier" />
      <Association Name="SETUP_Company_SETUP_SupplierType" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_SupplierType" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_VoucherType" Member="SETUP_VoucherTypes">
    <Type Name="SETUP_VoucherType">
      <Column Name="VchrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VchrType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrType_Prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_CodeInitialization" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_VoucherType_GL_VchrMaster" Member="GL_VchrMasters" ThisKey="VchrType_Id" OtherKey="VchrType_Id" Type="GL_VchrMaster" />
      <Association Name="SETUP_VoucherType_SETUP_VoucherTypeNarration" Member="SETUP_VoucherTypeNarrations" ThisKey="VchrType_Id" OtherKey="VchrType_Id" Type="SETUP_VoucherTypeNarration" />
      <Association Name="SETUP_Company_SETUP_VoucherType" Member="SETUP_Company" ThisKey="Cmp_Id" OtherKey="Cmp_Id" Type="SETUP_Company" IsForeignKey="true" />
      <Association Name="SETUP_Location_SETUP_VoucherType" Member="SETUP_Location" ThisKey="Loc_Id" OtherKey="Loc_Id" Type="SETUP_Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SETUP_VoucherTypeNarration" Member="SETUP_VoucherTypeNarrations">
    <Type Name="SETUP_VoucherTypeNarration">
      <Column Name="VchrTypeNarr_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VchrTypeNarr_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchrTypeNarr_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrTypeNarr_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrTypeNarr_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SETUP_VoucherType_SETUP_VoucherTypeNarration" Member="SETUP_VoucherType" ThisKey="VchrType_Id" OtherKey="VchrType_Id" Type="SETUP_VoucherType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYSTEM_AccountNature" Member="SYSTEM_AccountNatures">
    <Type Name="SYSTEM_AccountNature">
      <Column Name="AccNatr_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccNatr_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccNatr_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AccNatr_Default" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccNatr_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SYSTEM_AccountNature_SETUP_ChartOfAccount" Member="SETUP_ChartOfAccounts" ThisKey="AccNatr_Id" OtherKey="AccNatr_Id" Type="SETUP_ChartOfAccount" />
    </Type>
  </Table>
  <Table Name="dbo.SYSTEM_CodeGeneration" Member="SYSTEM_CodeGenerations">
    <Type Name="SYSTEM_CodeGeneration">
      <Column Name="CodeGen_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CodeGen_TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodeGen_ColumnName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodeGen_Prefix" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="CodeGen_Length" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodeGen_AutoTag" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetCityList" Method="sp_GetCityList">
    <ElementType Name="sp_GetCityListResult">
      <Column Name="City_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cnty_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_VoucherEntryConsole" Method="sp_VoucherEntryConsole">
    <Parameter Name="AllLocation" Parameter="allLocation" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocationId" Parameter="locationId" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="AllVoucherType" Parameter="allVoucherType" Type="System.Int32" DbType="Int" />
    <Parameter Name="VoucherTypeId" Parameter="voucherTypeId" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="AllDate" Parameter="allDate" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateFrom" Parameter="dateFrom" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="DateTo" Parameter="dateTo" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="sp_VoucherEntryConsoleResult">
      <Column Name="Loc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchMas_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchMas_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchMas_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VchMas_Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VchMas_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetCompanyList" Method="sp_GetCompanyList">
    <ElementType Name="sp_GetCompanyListResult">
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cmp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Phone" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Fax" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cmp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetLocationList" Method="sp_GetLocationList">
    <ElementType Name="sp_GetLocationListResult">
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Loc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loc_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cmp_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cmp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Phone" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Fax" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cmp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetUserGroupList" Method="sp_GetUserGroupList">
    <ElementType Name="sp_GetUserGroupListResult">
      <Column Name="UsrGrp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UsrGrp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsrGrp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UsrGrp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsrGrp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetUserList" Method="sp_GetUserList">
    <ElementType Name="sp_GetUserListResult">
      <Column Name="User_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsrGrp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="User_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="User_Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="User_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsrGrp_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UsrGrp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsrGrp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UsrGrp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsrGrp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetUserMenuRights" Method="sp_GetUserMenuRights">
    <Parameter Name="GroupId" Parameter="groupId" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_GetUserMenuRightsResult">
      <Column Name="Mnu_Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Mnu_Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Mnu_Level" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SelectedMenu" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetVoucherTypeNarrationList" Method="sp_GetVoucherTypeNarrationList">
    <ElementType Name="sp_GetVoucherTypeNarrationListResult">
      <Column Name="VchrTypeNarr_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchrTypeNarr_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchrTypeNarr_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrTypeNarr_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrTypeNarr_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchrType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrType_Prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_CodeInitialization" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetVoucherTypesList" Method="sp_GetVoucherTypesList">
    <ElementType Name="sp_GetVoucherTypesListResult">
      <Column Name="VchrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchrType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrType_Prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_CodeInitialization" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loc_Id1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Loc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loc_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PopulateCityList" Method="sp_PopulateCityList">
    <ElementType Name="sp_PopulateCityListResult">
      <Column Name="City_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cnty_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PopulateCompanyList" Method="sp_PopulateCompanyList">
    <ElementType Name="sp_PopulateCompanyListResult">
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cmp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Phone" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Fax" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cmp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cmp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PopulateLocationList" Method="sp_PopulateLocationList">
    <ElementType Name="sp_PopulateLocationListResult">
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Loc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loc_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PopulateUserGroupList" Method="sp_PopulateUserGroupList">
    <ElementType Name="sp_PopulateUserGroupListResult">
      <Column Name="UsrGrp_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UsrGrp_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsrGrp_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UsrGrp_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsrGrp_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PopulateUserList" Method="sp_PopulateUserList">
    <ElementType Name="sp_PopulateUserListResult">
      <Column Name="User_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsrGrp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="User_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="User_Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="User_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PopulateVoucherTypeList" Method="sp_PopulateVoucherTypeList">
    <ElementType Name="sp_PopulateVoucherTypeListResult">
      <Column Name="VchrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchrType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrType_Prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_CodeInitialization" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReportLedgerDetail" Method="sp_ReportLedgerDetail">
    <ElementType Name="sp_ReportLedgerDetailResult">
      <Column Name="VchMas_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchMas_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchMas_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cmp_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchMas_Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VchMas_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchMas_EnteredBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchMas_EnteredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VchMas_ApprovedBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchMas_ApprovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VchDet_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchMas_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChrtAcc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchMas_DrAmount" Type="System.Decimal" DbType="Decimal(20,6)" CanBeNull="true" />
      <Column Name="VchMas_CrAmount" Type="System.Decimal" DbType="Decimal(20,6)" CanBeNull="true" />
      <Column Name="VchDet_Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Loc_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Loc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Loc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loc_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VchrType_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchrType_Prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VchrType_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VchrType_CodeInitialization" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_Id1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChrtAcc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cmp_Id3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Loc_Id3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Natr_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccNatr_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChrtAcc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ChrtAcc_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_BudgetLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReportTrialBalance" Method="sp_ReportTrialBalance">
    <Parameter Name="AllLocation" Parameter="allLocation" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocationId" Parameter="locationId" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="AllVoucherType" Parameter="allVoucherType" Type="System.Int32" DbType="Int" />
    <Parameter Name="VoucherTypeId" Parameter="voucherTypeId" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="AllDate" Parameter="allDate" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateFrom" Parameter="dateFrom" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="DateTo" Parameter="dateTo" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="sp_ReportTrialBalanceResult">
      <Column Name="ChrtAcc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChrtAcc_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChrtAcc_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VchMas_DrAmount" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
      <Column Name="VchMas_CrAmount" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReportChartOfAccount" Method="sp_ReportChartOfAccount">
    <Parameter Name="Level" Parameter="level" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ReportChartOfAccountResult">
      <Column Name="ChrtAcc_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChrtAcc_Code" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="ChrtAcc_Title" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="ChrtAcc_Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_BudgetLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrtAcc_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Natr_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AccNatr_Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>